# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5827fe5e8f0858c58a1f3e00c25b1f0e36ce233706c088dbf7ba266ed4638554a3ce37597ea8430d810ed65237bda29eb0abad7a0e6a7356ca8ccf18fdc603b7

test:
  secret_key_base: 8a5da36862fce02b3bee8a1e8fbc520d554c59af6d91fda4394b67f922c44339f8615a5294c8003a2e05c68a3176a9f573cc7e9836514f3a8a8fcae7868aa214

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
